#!/bin/bash
echo
echo "---------------"
echo "Fail2Ban report"
echo "---------------"
echo
echo "Last 20 lines of fail2ban.log"
echo "-----------------------------"
cat /var/log/fail2ban.log | tail -n 20 
echo
echo "fail2ban service status"
echo "-----------------------"
sudo fail2ban-client status ssh
echo

