#!/bin/bash

echo
echo "Invalid user access report"
echo
echo "Number of invalid user logins: "$(cat /var/log/auth.log | grep 'invalid user\|Failed' | wc -l)
echo
echo "Last 20 failed logins"
cat /var/log/auth.log | grep 'invalid user\|Failed' | tail -n 20
echo
exit 0


